[package]
name = "read-conf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
utils = { path = "../../../lib/utils" }
conf = { path = "../../../lib/conf" }